### ISSUE TITLE
Creating memory sections

### ISSUE THREAD

**Issue by yigity19** [mbaykenar/zynq-soc-hw-sw-design#1]
Hello, 

Is there any advantage of creating memory sections rather than using memory pointers. For example I thought of creating a memory pointer like this

#define OCM_PTR (unsigned int*)(0xFFFF0000)

then incrementing it until the constant array size.

**Comment by mbaykenar** [comment]
Hi,

I don't think there will be any advantage with respect to performance. This is how I handled the situation, I am not sure but I got some errors on memory accessing with pointers and then come up with this idea. Please inform me if your method also works correctly.

Regards,

**Comment by yigity19** [comment]
Yes, it does work correctly. I saw it for the first time while I was searching for dual-core applications for Zynq-7000 [on this blog](https://www.hackster.io/whitney-knitter/dual-arm-hello-world-on-zynq-using-vitis-9fc8b7).

But it is a much more manual way. Every time a new variable is declared, the address is also must be incremented by the size of the previous variable. In addition, declaring arrays is also a problem. Therefore, using the linker script to reserve memory space for variables is much more practical. 

Thank you for the open-source high-quality lectures on Youtube.
